-- Drop the PETRESCUE table in case it exists
drop table PETRESCUE;
-- Create the PETRESCUE table 
create table PETRESCUE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	COST DECIMAL(6,2),
	RESCUEDATE DATE,
	PRIMARY KEY (ID)
	);
-- Insert sample data into PETRESCUE table
insert into PETRESCUE values 
	(1,'Cat',9,450.09,'2018-05-29'),
	(2,'Dog',3,666.66,'2018-06-01'),
	(3,'Dog',1,100.00,'2018-06-04'),
	(4,'Parrot',2,50.00,'2018-06-04'),
	(5,'Dog',1,75.75,'2018-06-10'),
	(6,'Hamster',6,60.60,'2018-06-11'),
	(7,'Cat',1,44.44,'2018-06-11'),
	(8,'Goldfish',24,48.48,'2018-06-14'),
	(9,'Dog',2,222.22,'2018-06-15')
	
--Aggregate--

SELECT SUM(COST) as COST_OF_PET FROM PETRESCUE

--QUERY2--
SELECT MAX(QUANTITY) FROM PETRESCUE;

--QUERY--
SELECT AVG(COST) FROM PETRESCUE

--QUERY4--
SELECT AVG(COST) FROM PETRESCUE WHERE ANIMAL='Dog'

--SCALAR AND STRING FUNCTIONS--
SELECT ROUND(COST) FROM PETRESCUE

--LENGTH--
SELECT LENGTH(ANIMAL) FROM PETRESCUE

--QUERY7--
SELECT UCASE(ANIMAL) FROM PETRESCUE

--QUERY8--
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE

--QUERY9--
SELECT * FROM PETRESCUE where LCASE(ANIMAL) = 'cat';

--DATEANDTIME--
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'Cat'

--query--
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE)=14

--QURTY--
SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE 

--QUERY--
SELECT (CURRENT_DATE - RESCUEDATE) FROM PETRESCUE


-- Drop the PETRESCUE table in case it exists
drop table PETRESCUE;
-- Create the PETRESCUE table 
create table PETRESCUE (
	ID INTEGER NOT NULL,
	ANIMAL VARCHAR(20),
	QUANTITY INTEGER,
	COST DECIMAL(6,2),
	RESCUEDATE DATE,
	PRIMARY KEY (ID)
	);
-- Insert sample data into PETRESCUE table
insert into PETRESCUE values 
	(1,'Cat',9,450.09,'2018-05-29'),
	(2,'Dog',3,666.66,'2018-06-01'),
	(3,'Dog',1,100.00,'2018-06-04'),
	(4,'Parrot',2,50.00,'2018-06-04'),
	(5,'Dog',1,75.75,'2018-06-10'),
	(6,'Hamster',6,60.60,'2018-06-11'),
	(7,'Cat',1,44.44,'2018-06-11'),
	(8,'Goldfish',24,48.48,'2018-06-14'),
	(9,'Dog',2,222.22,'2018-06-15')
	
--Aggregate--

SELECT SUM(COST) as COST_OF_PET FROM PETRESCUE

--QUERY2--
SELECT MAX(QUANTITY) FROM PETRESCUE;

--QUERY--
SELECT AVG(COST) FROM PETRESCUE

--QUERY4--
SELECT AVG(COST) FROM PETRESCUE WHERE ANIMAL='Dog'

--SCALAR AND STRING FUNCTIONS--
SELECT ROUND(COST) FROM PETRESCUE

--LENGTH--
SELECT LENGTH(ANIMAL) FROM PETRESCUE

--QUERY7--
SELECT UCASE(ANIMAL) FROM PETRESCUE

--QUERY8--
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE

--QUERY9--
SELECT * FROM PETRESCUE where LCASE(ANIMAL) = 'cat';

--DATEANDTIME--
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'Cat'

--query--
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE)=14

--QURTY--
SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE 

--QUERY--
SELECT (CURRENT_DATE - RESCUEDATE) FROM PETRESCUE


